"""Add temporal tracking columns to Arena, Team, and Person

Revision ID: 4a14fd7e5fef
Revises: 5869dcf524f5
Create Date: 2025-09-02 10:20:38.145095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a14fd7e5fef'
down_revision: Union[str, None] = '5869dcf524f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('first_used', sa.DateTime(), nullable=True))
    op.add_column('arena', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('person', sa.Column('first_used', sa.DateTime(), nullable=True))
    op.add_column('person', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('team', sa.Column('first_used', sa.DateTime(), nullable=True))
    op.add_column('team', sa.Column('last_used', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'last_used')
    op.drop_column('team', 'first_used')
    op.drop_column('person', 'last_used')
    op.drop_column('person', 'first_used')
    op.drop_column('arena', 'last_used')
    op.drop_column('arena', 'first_used')
    # ### end Alembic commands ###
