"""add final scores and winner to game table

Revision ID: 759dd870d75c
Revises: da3c2cab9f79
Create Date: 2025-09-04 16:12:49.538846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759dd870d75c'
down_revision: Union[str, None] = 'da3c2cab9f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('final_home_score', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('final_away_score', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('winner', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'winner')
    op.drop_column('game', 'final_away_score')
    op.drop_column('game', 'final_home_score')
    # ### end Alembic commands ###
