"""Add season and game_type columns to game table

Revision ID: 92e507f9b7ec
Revises: ce826a328e01
Create Date: 2025-09-03 19:53:59.021102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e507f9b7ec'
down_revision: Union[str, None] = 'ce826a328e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('game_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'game_type')
    op.drop_column('game', 'season')
    # ### end Alembic commands ###
