"""Change game_data from Text to JSONB

Revision ID: b91291bee5e8
Revises: f9c3b8d93289
Create Date: 2025-08-27 20:38:34.890213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b91291bee5e8'
down_revision: Union[str, None] = 'f9c3b8d93289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE raw_game_data ALTER COLUMN game_data TYPE JSONB USING game_data::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE raw_game_data ALTER COLUMN game_data TYPE TEXT USING game_data::text")
    # ### end Alembic commands ###
