"""add efg and tsp columns to boxscore table

Revision ID: da3c2cab9f79
Revises: 92e507f9b7ec
Create Date: 2025-09-04 16:09:05.918206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3c2cab9f79'
down_revision: Union[str, None] = '92e507f9b7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxscore', sa.Column('efg', sa.Float(), nullable=True))
    op.add_column('boxscore', sa.Column('tsp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxscore', 'tsp')
    op.drop_column('boxscore', 'efg')
    # ### end Alembic commands ###
