"""Added season and game type to raw game data

Revision ID: debd2ca4a93b
Revises: b91291bee5e8
Create Date: 2025-08-27 20:46:46.979609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debd2ca4a93b'
down_revision: Union[str, None] = 'b91291bee5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values first, then make them NOT NULL
    op.add_column('raw_game_data', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('raw_game_data', sa.Column('game_type', sa.String(length=20), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE raw_game_data SET season = 2024 WHERE season IS NULL")
    op.execute("UPDATE raw_game_data SET game_type = 'regular' WHERE game_type IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('raw_game_data', 'season', nullable=False)
    op.alter_column('raw_game_data', 'game_type', nullable=False)
    
    # Convert game_id to integer
    op.execute("ALTER TABLE raw_game_data ALTER COLUMN game_id TYPE INTEGER USING game_id::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE raw_game_data ALTER COLUMN game_id TYPE VARCHAR(50) USING game_id::varchar")
    op.drop_column('raw_game_data', 'game_type')
    op.drop_column('raw_game_data', 'season')
    # ### end Alembic commands ###
