"""Add raw_game_data table and fix timestamp defaults

Revision ID: f9c3b8d93289
Revises: a7dbe02b90fc
Create Date: 2025-08-27 20:37:43.578383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c3b8d93289'
down_revision: Union[str, None] = 'a7dbe02b90fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('game_url', sa.String(length=500), nullable=False),
    sa.Column('game_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_game_data_game_id'), 'raw_game_data', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_game_data_game_id'), table_name='raw_game_data')
    op.drop_table('raw_game_data')
    # ### end Alembic commands ###
